#ifndef _PONY_LIBPONYRT_COMMON_H_
#define _PONY_LIBPONYRT_COMMON_H_

#ifdef USE_VALGRIND
#include <valgrind/helgrind.h>
#define PONYINT_ANNOTATE_HAPPENS_BEFORE(...)  PONYINT_ANNOTATE_HAPPENS_BEFORE(__VA_ARGS__)
#define PONYINT_ANNOTATE_HAPPENS_AFTER(...)   ANNOTATE_HAPPENS_AFTER(__VA_ARGS__)
#else
#define PONYINT_ANNOTATE_HAPPENS_AFTER(...)
#define PONYINT_ANNOTATE_HAPPENS_BEFORE(...)
#endif

#endif /* _PONY_LIBPONYRT_COMMON_H_ */